#define PIN_77HC165_QH            8
#define PIN_77HC165_SH_LD         9
#define PIN_77HC165_CLK_INH      10
#define PIN_77HC165_CLK          12

#define DELAY_77HC165             5

#define BIT_ICP_COM1_BTN                     1
#define BIT_ICP_COM2_BTN                     2
#define BIT_ICP_IFF_BTN                      3
#define BIT_ICP_LIST_BTN                     4
#define BIT_ICP_AA_MODE_BTN                  5
#define BIT_ICP_AG_MODE_BTN                  6
#define BIT_ICP_BTN_1                       12
#define BIT_ICP_BTN_2                       13
#define BIT_ICP_BTN_3                       14
#define BIT_ICP_BTN_4                        8
#define BIT_ICP_BTN_5                        9
#define BIT_ICP_BTN_6                       10
#define BIT_ICP_BTN_7                       20
#define BIT_ICP_BTN_8                       21
#define BIT_ICP_BTN_9                       22
#define BIT_ICP_BTN_0                       23
#define BIT_ICP_RCL_BTN                     15
#define BIT_ICP_ENTR_BTN                    11
#define BIT_ICP_WX_BTN                       0
#define BIT_ICP_DATA_UP_DN_SW_UP            27
#define BIT_ICP_DATA_UP_DN_SW_DN            25
#define BIT_ICP_DATA_RTN_SEQ_SW_RNT         26
#define BIT_ICP_DATA_RTN_SEQ_SW_SEQ         24
#define BIT_ICP_DRIFT_SW_DRIFT              28
#define BIT_BIT_ICP_DRIFT_SW_DRIFT_WARN     29
#define BIT_ICP_FLIR_GAIN_SW_GAIN           30
#define BIT_ICP_FLIR_GAIN_SW_AUTO           31
#define BIT_ICP_FLIR_SW_UP                  17
#define BIT_ICP_FLIR_SW_DN                  16
#define BIT_ICP_DED_SW_UP                   19
#define BIT_ICP_DED_SW_DN                   18